const data = [
  {
    id: 2797453,
    ast: 0,
    blk: 1,
    dreb: 6,
    fg3_pct: 75.0,
    fg3a: 4,
    fg3m: 3,
    fg_pct: 53.8,
    fga: 13,
    fgm: 7,
    ft_pct: 75.0,
    fta: 8,
    ftm: 6,
    game: {
      id: 117691,
      date: '2020-08-19T00:00:00.000Z',
      home_team_id: 13,
      home_team_score: 114,
      period: 4,
      postseason: true,
      season: 2019,
      status: 'Final',
      time: '',
      visitor_team_id: 7,
      visitor_team_score: 127,
    },
    min: '36:11',
    oreb: 1,
    pf: 4,
    player: {
      id: 378,
      first_name: 'Kristaps',
      height_feet: 7,
      height_inches: 3,
      last_name: 'Porzingis',
      position: 'F-C',
      team_id: 30,
      weight_pounds: 240,
    },
    pts: 23,
    reb: 7,
    stl: 0,
    team: {
      id: 7,
      abbreviation: 'DAL',
      city: 'Dallas',
      conference: 'West',
      division: 'Southwest',
      full_name: 'Dallas Mavericks',
      name: 'Mavericks',
    },
    turnover: 2,
  },
  {
    id: 2806492,
    ast: 1,
    blk: 1,
    dreb: 11,
    fg3_pct: 55.6,
    fg3a: 9,
    fg3m: 5,
    fg_pct: 61.1,
    fga: 18,
    fgm: 11,
    ft_pct: 100.0,
    fta: 7,
    ftm: 7,
    game: {
      id: 117701,
      date: '2020-08-21T00:00:00.000Z',
      home_team_id: 7,
      home_team_score: 122,
      period: 4,
      postseason: true,
      season: 2019,
      status: 'Final',
      time: '',
      visitor_team_id: 13,
      visitor_team_score: 130,
    },
    min: '38:21',
    oreb: 2,
    pf: 3,
    player: {
      id: 378,
      first_name: 'Kristaps',
      height_feet: 7,
      height_inches: 3,
      last_name: 'Porzingis',
      position: 'F-C',
      team_id: 30,
      weight_pounds: 240,
    },
    pts: 34,
    reb: 13,
    stl: 0,
    team: {
      id: 7,
      abbreviation: 'DAL',
      city: 'Dallas',
      conference: 'West',
      division: 'Southwest',
      full_name: 'Dallas Mavericks',
      name: 'Mavericks',
    },
    turnover: 1,
  },
  {
    id: 2791357,
    ast: 1,
    blk: 1,
    dreb: 6,
    fg3_pct: 25.0,
    fg3a: 4,
    fg3m: 1,
    fg_pct: 33.3,
    fga: 9,
    fgm: 3,
    ft_pct: 87.5,
    fta: 8,
    ftm: 7,
    game: {
      id: 117685,
      date: '2020-08-17T00:00:00.000Z',
      home_team_id: 13,
      home_team_score: 118,
      period: 4,
      postseason: true,
      season: 2019,
      status: 'Final',
      time: '',
      visitor_team_id: 7,
      visitor_team_score: 110,
    },
    min: '19:49',
    oreb: 0,
    pf: 2,
    player: {
      id: 378,
      first_name: 'Kristaps',
      height_feet: 7,
      height_inches: 3,
      last_name: 'Porzingis',
      position: 'F-C',
      team_id: 30,
      weight_pounds: 240,
    },
    pts: 14,
    reb: 6,
    stl: 0,
    team: {
      id: 7,
      abbreviation: 'DAL',
      city: 'Dallas',
      conference: 'West',
      division: 'Southwest',
      full_name: 'Dallas Mavericks',
      name: 'Mavericks',
    },
    turnover: 0,
  },
  {
    id: 2812823,
    ast: 0,
    blk: 0,
    dreb: 0,
    fg3_pct: 0.0,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.0,
    fga: 0,
    fgm: 0,
    ft_pct: 0.0,
    fta: 0,
    ftm: 0,
    game: {
      id: 117709,
      date: '2020-08-23T00:00:00.000Z',
      home_team_id: 7,
      home_team_score: 135,
      period: 5,
      postseason: true,
      season: 2019,
      status: 'Final',
      time: '',
      visitor_team_id: 13,
      visitor_team_score: 133,
    },
    min: '',
    oreb: 0,
    pf: 0,
    player: {
      id: 378,
      first_name: 'Kristaps',
      height_feet: 7,
      height_inches: 3,
      last_name: 'Porzingis',
      position: 'F-C',
      team_id: 30,
      weight_pounds: 240,
    },
    pts: 0,
    reb: 0,
    stl: 0,
    team: {
      id: 7,
      abbreviation: 'DAL',
      city: 'Dallas',
      conference: 'West',
      division: 'Southwest',
      full_name: 'Dallas Mavericks',
      name: 'Mavericks',
    },
    turnover: 0,
  },
];
